-- Issue #22: 裏商品「ミステリーボックス」機能の実装に伴うテーブル変更

-- ①itemsテーブルに裏メニューフラグを追加
ALTER TABLE items ADD is_secret NUMBER(1) DEFAULT 0 NOT NULL;

-- ②「裏メニュー」カテゴリの登録
INSERT INTO categories (id, name, delete_flag, insert_date)
VALUES (seq_categories.NEXTVAL, '裏メニュー', 0, CURRENT_DATE);

-- ③order_itemsテーブルにミステリーボックス由来フラグと景品IDを追加
ALTER TABLE order_items ADD is_mystery      NUMBER(1) DEFAULT 0 NOT NULL;
ALTER TABLE order_items ADD mystery_item_id NUMBER;

-- ④ミステリーボックス専用景品テーブルの新規作成
CREATE TABLE mystery_items (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR2(200)  NOT NULL,
    description VARCHAR2(1000),
    rank        VARCHAR2(1)    NOT NULL CHECK (rank IN ('S', 'A', 'B', 'C')),
    delete_flag NUMBER(1) DEFAULT 0 NOT NULL
);
CREATE SEQUENCE seq_mystery_items START WITH 1 INCREMENT BY 1;

-- ⑤グレード別ランク出現ウェイトテーブルの新規作成
--   weight合計は各gradeで100となるように設定する
CREATE TABLE mystery_item_weights (
    id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rank   VARCHAR2(1) NOT NULL CHECK (rank IN ('S', 'A', 'B', 'C')),
    grade  NUMBER      NOT NULL CHECK (grade IN (1000, 10000)),
    weight NUMBER(3)   NOT NULL,
    CONSTRAINT uq_weight_rank_grade UNIQUE (rank, grade)
);

-- ⑥order_itemsのmystery_item_idに外部キー制約を追加
ALTER TABLE order_items
    ADD CONSTRAINT fk_order_item_mystery
    FOREIGN KEY (mystery_item_id) REFERENCES mystery_items(id);

-- ⑦ミステリーボックス商品の登録（2グレード）
INSERT INTO items (id, name, price, stock, description, image, category_id, is_secret)
VALUES (
    seq_items.NEXTVAL,
    'ミステリーボックス（1,000円）',
    1000,
    999,
    '中身がランダムで決まるお楽しみボックス！1,000円グレードです。',
    NULL,
    (SELECT id FROM categories WHERE name = '裏メニュー'),
    1
);
INSERT INTO items (id, name, price, stock, description, image, category_id, is_secret)
VALUES (
    seq_items.NEXTVAL,
    'ミステリーボックス（10,000円）',
    10000,
    999,
    '中身がランダムで決まるお楽しみボックス！10,000円グレードはレア景品の出現率アップ！',
    NULL,
    (SELECT id FROM categories WHERE name = '裏メニュー'),
    1
);

-- ⑧グレード別ランク出現ウェイトの登録
-- 1,000円グレード（S=1, A=5, B=19, C=75　合計100）
INSERT INTO mystery_item_weights (rank, grade, weight) VALUES ('S', 1000,  1);
INSERT INTO mystery_item_weights (rank, grade, weight) VALUES ('A', 1000,  5);
INSERT INTO mystery_item_weights (rank, grade, weight) VALUES ('B', 1000, 19);
INSERT INTO mystery_item_weights (rank, grade, weight) VALUES ('C', 1000, 75);
-- 10,000円グレード（S=10, A=20, B=30, C=40　合計100）
INSERT INTO mystery_item_weights (rank, grade, weight) VALUES ('S', 10000, 10);
INSERT INTO mystery_item_weights (rank, grade, weight) VALUES ('A', 10000, 20);
INSERT INTO mystery_item_weights (rank, grade, weight) VALUES ('B', 10000, 30);
INSERT INTO mystery_item_weights (rank, grade, weight) VALUES ('C', 10000, 40);

-- ⑨景品データの登録（全16件）
-- Sランク（2件）
INSERT INTO mystery_items (name, description, rank)
    VALUES ('Nintendo Switch本体セット',  '人気ゲーム機本体。何でも遊べる夢のセット！',        'S');
INSERT INTO mystery_items (name, description, rank)
    VALUES ('高級ワイヤレスイヤホン',      'ノイズキャンセリング機能搭載の高音質イヤホン。',    'S');
-- Aランク（4件）
INSERT INTO mystery_items (name, description, rank)
    VALUES ('人気漫画全巻セット',          '話題の漫画が全巻揃い踏み！',                       'A');
INSERT INTO mystery_items (name, description, rank)
    VALUES ('ブランドポーチセット',        '人気ブランドの使いやすいポーチ3点セット。',         'A');
INSERT INTO mystery_items (name, description, rank)
    VALUES ('コーヒーメーカー',            '自宅で本格コーヒーが楽しめる一台。',               'A');
INSERT INTO mystery_items (name, description, rank)
    VALUES ('映画鑑賞ペアチケット',        '話題の映画館で使えるペアチケット。',               'A');
-- Bランク（5件）
INSERT INTO mystery_items (name, description, rank)
    VALUES ('人気お菓子詰め合わせセット',  '国内外の人気お菓子をたっぷり詰め込みました。',     'B');
INSERT INTO mystery_items (name, description, rank)
    VALUES ('タオルハンカチ3枚セット',     'やわらかな肌触りの今治タオルハンカチ。',           'B');
INSERT INTO mystery_items (name, description, rank)
    VALUES ('スマートフォンスタンド',      '角度調整可能なアルミ製スタンド。',                 'B');
INSERT INTO mystery_items (name, description, rank)
    VALUES ('キャラクターマグカップ',      '人気キャラクターデザインのマグカップ。',            'B');
INSERT INTO mystery_items (name, description, rank)
    VALUES ('読書ライト',                  '目に優しいLED読書ライト。クリップ式。',            'B');
-- Cランク（5件）
INSERT INTO mystery_items (name, description, rank)
    VALUES ('ボールペンセット',            '書きやすい国産ボールペン5本セット。',              'C');
INSERT INTO mystery_items (name, description, rank)
    VALUES ('付箋セット',                  'カラフルな付箋がたっぷり入ったセット。',           'C');
INSERT INTO mystery_items (name, description, rank)
    VALUES ('キーホルダー',                '金属製のシンプルなキーホルダー。',                 'C');
INSERT INTO mystery_items (name, description, rank)
    VALUES ('クリアファイル3枚セット',     'A4サイズのクリアファイル。書類整理に。',           'C');
INSERT INTO mystery_items (name, description, rank)
    VALUES ('メモ帳',                      '持ち運びに便利なA6サイズのメモ帳。',              'C');

COMMIT;
