#クローン後は右クリック>>チーム>>無視 でコミットから外すこと

server.servlet.context-path=/shared_shop
server.port=55000
spring.thymeleaf.cache=false

# H2 Database (Sandbox fallback)
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=Oracle
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.defer-datasource-initialization=true

# Oracle configuration (Original)
#spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
#spring.datasource.url=jdbc:oracle:thin:@localhost:1521/xepdb1
#spring.datasource.username=shared_shop_user
#spring.datasource.password=systemsss

##SQL文をコンソールに表示するための設定
# SQL文をコンソール出力する
logging.level.org.hibernate.SQL=debug

# 【SpringBoot3.x～】バインドパラメータ（値）を出力する
logging.level.org.hibernate.orm.jdbc.bind=trace

#出力するSQLを整形する
spring.jpa.properties.hibernate.format_sql=true

###
# 以下、商品画像アップロードに関する設定
###
 # Intermediate location of uploaded files.
spring.servlet.multipart.location=${user.dir}/temp
 # Max file size.
spring.servlet.multipart.max-file-size=1MB
 #
spring.servlet.multipart.max-request-size=10MB

#Default Servletコンテナの有効化
server.servlet.register-default-servlet=true

##ここまで
